### ISSUE TITLE
Iterative Training of V?

### ISSUE THREAD

**Issue by ppkn** [worldmodels/worldmodels.github.io#7]
I like the discussion of an iterative training procedure with M and C, but is it also possible to train the VAE during this iterative process as well? Actively exploring parts of the environment is likely improve the visual part of the world model as the agent discovers new areas.

I'm guessing some thought was put into this that just didn't make it into the final draft of the paper.

**Comment by hardmaru** [comment]
Hi @dpipkin

Thanks for the message. Not all environments have pixel observations, so in general V may not be needed. So when we wrote that section on iterative training, M is meant to be more general and include V as well. The notion that M includes V originated from the [Learning to Think](https://arxiv.org/abs/1511.09249) paper, but when I was writing this article and designing the experiments, I think it is more clear to explicitly separate V as well. Apologies for the confusion!
